### ISSUE TITLE
Serial Control Type

### ISSUE THREAD

**Issue by WhileE** [AterialDawn/Nintendo-Switch-Pro-Controller-AVR-Firmware#2]
I was looking into PRO controller emulation via AVR and stumbled across this great piece of work, thank you BTW, I started dumping and analyzing the USB protocol and this just saved me so much time.  I had no other means of getting in touch with you, but wanted to inquire as to how you're controlling this emulator?  
  
It looks as though you're using a serial protocol of sorts to control it, but I'm curious if that's a PC based application or if you're doing something like using another AVR (maybe the 328p) to control this. I'm generally just curious about any lag you're experiencing if you're using something like a PC based application.  
  
I was previously emulating the POKKEN controller, and analyzing keyboard/mouse comm through the 16u2, and it as very snappy, but if it's just as good using a PC I may as well move do something like that. 
  
Thanks again for the hard work!

**Comment by AterialDawn** [comment]
I used a PC app for this, captured keyboard+mouse and converted it to controller update packets sent over serial. Latency was pretty good, only a slight increase in latency over the actual controller, perfectly playable on splatoon when I tested it a while ago.

**Comment by WhileE** [comment]
Interesting. I may have to experiment with this. I'm currently using keyboard/mouse that speak PS2, therefore I can integrate directly with them without the need for a USB host layer. Currently running everything from the 16u2 that lives on the Arduino Uno R3. With my current setup it's emulating the POKKEN controller, and there's virtually no visible latency that I can tell. I'm interested in moving this direction to use mouse<->motion instead of stick, which I would assume is head and shoulders better. Not sure if I want to go the PC app route, or something like USB host shield <-> 328p <-> 16u2 setup. I imaging it would be more work going with the host shield, but it would likely run faster than the PC due to the OS overhead.  
  
I actually just pulled, built, and flashed to the 16u2 and the switch didn't want to recognize it. Not sure what went wrong but will dump the traffic tonight to see if I can nail it down. I don't have a serial controller setup at the moment, but imagine it should still enumerate just fine without it.
